#Default properties configuration
#Mon Mar 09 18:08:10 CET 2026
app.height=700
app.title=HR App
app.width=1100
db.url=jdbc\:sqlite\:hrapp.db
divider.position=0.35
grade.max=10
grade.min=1
log.dir=/Users/djradovic/hrapp-logs
max.comment.length=500
max.name.length=100
max.skill.length=100
max.task.name.length=200
